### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by edenlith** [hdb/qtube#3]
I know this might be a long shot since this repository looks like it isn't being maintained anymore.

When I try to install the requirements I get this output: 

~/qtube$ pip install -r requirements.txt
Collecting QTWaitingSpinner
  Cloning git://github.com/z3ntu/QtWaitingSpinner.git (to revision master) to /tmp/pip-install-cl0lcs12/qtwaitingspinner_a3f53ad8ca124dbe80d43c7529d7e75e
  Running command git clone --filter=blob:none --quiet git://github.com/z3ntu/QtWaitingSpinner.git /tmp/pip-install-cl0lcs12/qtwaitingspinner_a3f53ad8ca124dbe80d43c7529d7e75e
  fatal: unable to connect to github.com:
  github.com[0: 140.82.121.4]: errno=Resource temporarily unavailable

  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet git://github.com/z3ntu/QtWaitingSpinner.git /tmp/pip-install-cl0lcs12/qtwaitingspinner_a3f53ad8ca124dbe80d43c7529d7e75e did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet git://github.com/z3ntu/QtWaitingSpinner.git /tmp/pip-install-cl0lcs12/qtwaitingspinner_a3f53ad8ca124dbe80d43c7529d7e75e did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: You are using pip version 22.0.4; however, version 23.2.1 is available.
You should consider upgrading via the '/home/user/.pyenv/versions/3.10.4/bin/python3.10 -m pip install --upgrade pip' command."

Can someone help me?

**Comment by hdb** [comment]
It looks like the issue is your ssh connection to Github.

If you don't have ssh configured for Github you can also just remove the line with the Github repo dependency from requirements.txt and manually install the dependency, e.g. over https instead of ssh:

~~git+git://github.com/z3ntu/QtWaitingSpinner.git@master#egg=QTWaitingSpinner~~

```
pip install git+https://github.com/z3ntu/QtWaitingSpinner.git
```
